
.test_cypress_base:
  image: registry.gitlab.inria.fr/vidjil/vidjil/cypress_with_browsers:$CYPRESS_DOCKER_VERSION
  stage: test_cypress_client
  # extends:
    # - .need_for_staged_client
  script:
    - echo -e "Run cypress with browser $BROWSER"
    - echo -e "PWD $PWD; CYPRESS_PATH $CYPRESS_PATH"
    # Create doc support files for testing
    - python tools/org-babel-tangle.py --all doc/vidjil-format.md
    - mv analysis-example1.vidjil  analysis-example2.analysis  analysis-example2.vidjil doc/
    # Cypress
    - bash docker/ci/script_preprocess.bash
    - cd /app
    - export BROWSER=browsers/$BROWSER
    - echo "TEST_FILES_PATTERN - $TEST_FILES_PATTERN"
    - bash script.bash "$TEST_FILES_PATTERN"
  variables:
    BROWSER: ../electron
    CYPRESS_PATH: browser/test/cypress
    HOST: html
    TEST_FILES_PATTERN: "/app/cypress/e2e/test_*.js"
  artifacts:
    reports:
      junit: $CYPRESS_PATH/reports/report_test_*.xml
    paths:
      - $CYPRESS_PATH
      - docker/volumes/vidjil/log
    expire_in: 7 day
    when: always
  tags:
    - cidocker



.test_cypress_ext:
  stage: test_cypress_external
  extends:
    - .test_cypress_base
  variables:
    TEST_FILES_PATTERN: "/app/cypress/e2e/external_*.js"


## cypress client
# For the moment, need to be into separate stage (https://gitlab.com/gitlab-org/gitlab/-/issues/30632)
client1-ff-supported:
  extends:
    - .test_cypress_base
    - .need_for_moderate_client
  variables:
    BROWSER: chrome_supported/chrome
  needs:
    - []
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: on_success


c2:
  extends:
    - .test_cypress_base
  parallel:
    matrix:
      - BROWSER: [
          firefox_latest/firefox,
          firefox_legacy/firefox,
          firefox_supported/firefox,
          chrome_latest/chrome,
          chrome_legacy/chrome
        ]
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: manual

external1-ff-supported:
  extends:
    - .test_cypress_ext
    - .need_for_moderate_client
  variables:
    BROWSER: chrome_supported/chrome
  needs:
    - []
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: on_success

external2:
  extends:
    - .test_cypress_ext
    - .need_for_staged_client
  parallel:
    matrix:
      - BROWSER: [
          firefox_latest/firefox,
          firefox_legacy/firefox,
          firefox_supported/firefox,
          chrome_latest/chrome,
          chrome_legacy/chrome
        ]
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: manual




## cypress client
# For the moment, need to be into separate stage (https://gitlab.com/gitlab-org/gitlab/-/issues/30632)
.tuto-client:
  stage: test_tutorial
  extends:
    - .test_cypress_base
  variables:
    PATH_CYPRESS: browser/test/cypress/integration/
    TEST_FILES_PATTERN: "/app/cypress/e2e/doc_*.js"
  before_script:
    - apt-get update && apt-get -y install pandoc
    - make -C doc/tutorial/ build_tutorial_cypress_client


tuto-c1-ff-supported:
  extends:
    - .tuto-client
    - .need_for_moderate_client
  variables:
    BROWSER: chrome_supported/chrome
  needs:
    - []
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /doc/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: on_success

tuto-c2:
  extends:
    - .tuto-client
    - .need_for_late_client
  parallel:
    matrix:
      - BROWSER: [
          firefox_latest/firefox,
          firefox_legacy/firefox,
          firefox_supported/firefox,
          chrome_latest/chrome,
          chrome_legacy/chrome
        ]
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*c.*\/.*$/'
      when: manual