[uwsgi]
socket = :8000
master = 1
processes = 6
chdir = /usr/share/vidjil/server/py4web/apps
pythonpath = /usr/share/vidjil/server/py4web
file = app.py
uid = www-data
gid = www-data
chmod-socket = 666
chown-socket = www-data:www-data
listen = 1024 # set max connections to 1024

; logs
ignore-write-errors = 1
ignore-sigpipe = 1
env = LANG=C.UTF-8 ; Prevent UnicodeEncodeError
disable-logging = true ; Do not log all requests (already logged anyway by nginx), but still log errors
log-4xx = true
log-5xx = true

; workers clean up
vacuum = 1 ; Delete sockets during shutdown
die-on-term = 1 ; Stop on sigterm
; --> disable to prevent warnings and possibly error on slow updates - harakiri = 3600 ; kill workers if longer than 1h
; --> causes huge latency on big files upload - post-buffering = 1 ; enable post buffering (to prevent warning and potential error with harakiri)
max-requests = 1000 ; Restart workers after this many requests
reload-on-rss = 2048 ; Restart workers after this much resident memory
reload-mercy = 60 ; How long to wait before forcefully killing workers
