generate_server_reproducibility_yml:
  stage: test_tools
  variables:
    REPEAT: 30
  script:
    - tools/repeat-ci.sh server/.gitlab-ci.yml $REPEAT .gitlab-ci.yml .test_server_base .test_cypress_base .setup_docker_server .test_server_base_dind .before_script_global .before_script_global_docker -- .gitlab-ci.yml browser/.gitlab-ci.yml | grep -v .need > server-repro.yml
  needs: []
  only:
    - /^feature-.*s.*\/.*$/
  artifacts:
    paths:
      - server-repro.yml

generate_client_reproducibility_yml:
  stage: test_tools
  variables:
    REPEAT: 30
  script:
    - tools/repeat-ci.sh browser/.gitlab-ci.yml $REPEAT .gitlab-ci.yml | grep -v .need > client-repro.yml
  needs: []
  only:
    - /^feature-.*c.*\/.*$/
  artifacts:
    paths:
      - client-repro.yml
      
server_reproducibility:
  stage: test_cypress_server
  needs: [generate_server_reproducibility_yml]
  trigger:
    include:
      - artifact: server-repro.yml
        job: generate_server_reproducibility_yml
    strategy: depend
  when: manual
  only:
    - /^feature-.*s.*\/.*$/
  allow_failure: true

client_reproducibility:
  stage: test_cypress_client
  needs: [generate_client_reproducibility_yml]
  trigger:
    include:
      - artifact: client-repro.yml
        job: generate_client_reproducibility_yml
    strategy: depend
  when: manual
  only:
    - /^feature-.*c.*\/.*$/
  allow_failure: true
  
