# In addition to the standard set of exclusions, omit some paths to apply on server py4web only
extend-exclude = ["algo", "browser", "germline", "packaging", "tools", "server/scripts-web2py", "server/tests"]
[lint]
# Add import fix
extend-select = ["I"]
# Exclude specific rules no relevant to the project
# Comparison to `None` with `==` or `!=` should be used instead of `is` or `is not` in pydal
# Comparison to `True` or `False` with `==` or `!=` should be used instead of `is` or `is not` in pydal
ignore = ["E711", "E712"]
