#!/bin/sh

dir=$(dirname $0)

germline_id=$(cat $dir/germline_id)

cat <<EOF
By downloading the IMGT germline databases (IMGT/GENE-DB), you
accept the IMGT® license: academic research only, provided that it is referred
to IMGT® and cited as "IMGT®, the international ImMunoGeneTics information
system® http://www.imgt.org (founder and director: Marie-Paule Lefranc,
Montpellier, France).  Lefranc, M.-P., IMGT®, the international ImMunoGeneTics
database, Nucl. Acids Res., 29, 207-209 (2001). PMID:11125093.

Otherwise please remove the files from your system.
EOF

wget -N http://www.vidjil.org/germlines/germline-${germline_id}.tar.gz
tar xzfv germline-${germline_id}.tar.gz --strip-components=1 germline/
