#!/bin/sh

set -e

dir=$(dirname $0)

germline_id=$(cat $dir/germline_id)

cat <<EOF
By downloading the IMGT germline databases (IMGT/GENE-DB), you
accept the IMGT® license:  the IMGT® software and data are provided to the academic users and NPO's (Not for Profit Organization(s)) under the CC BY-NC-ND 4.0 license. Any other use of IMGT® material, from the private sector, needs a financial arrangement with CNRS. Citing IMGT-GENEDB: Giudicelli V., Chaume D. and Lefranc M.-P. IMGT/GENE-DB: a comprehensive database for human and mouse immunoglobulin and T cell receptor genes Nucl. Acids Res., 33(S1):D256-D261 (2005). PMID:15608191

Otherwise please remove the files from your system.
EOF

wget --no-check-certificate -N https://www.vidjil.org/germlines/germline-${germline_id}.tar.gz
tar xzmfv germline-${germline_id}.tar.gz --strip-components=1 germline/
if [ -d "$dir/../browser" ]; then
    tar xzmfv germline-${germline_id}.tar.gz --strip-components=1 -C $dir/../browser/ browser/
fi
