version: '3.3'

# ## Docker-compose
# You can set variables (as $MYSQL_ROOT_PASSWORD) values inside .env file
# Path variable and folders trees can be modified to your liking.

services:
    mysql2:
        container_name: vidjil-mysql2
        image: mysql:5.7
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME MYSQL
        env_file:
            - '.env-default'
            - '.env'
        volumes:
            - ./mysql/:/docker-entrypoint-initdb.d/
            - $VOLUME_PATH2/mysql:/var/lib/mysql
        ports:
            - "4307:3306"
            - "43070:33060"
        healthcheck:
            test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
            timeout: 5s
            start_period: 30s
            retries: 40
        networks:
            - vidjil2

    redis2:
        container_name: vidjil-redis2
        image: redis
        restart: always
        ports:
            - '6380:6379'
        networks:
            - vidjil2

    uwsgi2:
        container_name: vidjil-uwsgi2
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME UWSGI
        env_file:
            - '.env-default'
            - '.env'
        command: bash /entrypoints/uwsgi-entrypoint.sh
        stdin_open: true
        tty: true
        healthcheck:
            test: "bash /healthchecks/healthcheck_uwsgi.bash"
            timeout: 20s
            start_period: 0s
            retries: 2
        depends_on:
            mysql2:
                condition: service_healthy
        links:
            - mysql2:mysql
        volumes:
            - ./vidjil-server/scripts:/entrypoints
            - ./vidjil-server/healthchecks:/healthchecks
            - ./vidjil-server/conf/defs.py:/usr/share/vidjil/server/py4web/apps/vidjil/defs.py
            - ./vidjil-server/conf/defs-tools.py:/usr/share/vidjil/tools/defs.py
            - ./scripts/:/usr/share/vidjil/tools/scripts
            - $VOLUME_PATH2/results:/mnt/result/results
            - $VOLUME_PATH2/tmp:/mnt/result/tmp
            - $VOLUME_PATH2/uploads:/mnt/upload/uploads
            - $VOLUME_PATH2/tools:/usr/share/tools
            - $VOLUME_PATH2/databases:/usr/share/vidjil/server/py4web/apps/vidjil/databases
            - $VOLUME_PATH2/log:/var/vidjil
            - $VOLUME_PATH2/log/uwsgi:/var/log/uwsgi
            - $VOLUME_PATH2/backup:/mnt/backup
        networks:
            - vidjil2

    fuse2:
        container_name: vidjil-fuse2
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME FUSE
        command: bash /entrypoints/fuse-entrypoint.sh
        env_file:
            - '.env-default'
            - '.env'
        volumes_from:
            - uwsgi2
        depends_on:
            mysql2:
                condition: service_healthy
            uwsgi2:
                condition: service_healthy
        links:
            - mysql2:mysql
            - redis2:redis
            - uwsgi2:uwsgi
        networks:
            - vidjil2

    nginx2:
        container_name: vidjil-nginx2
        image: vidjil/client:latest
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME NGINX
        env_file:
            - '.env-default'
            - '.env'
        ports:
            - "81:80"
            - "8000:443"
        command: bash -c "make -C /usr/share/vidjil browser && bash /entrypoints/nginx-entrypoint.sh"
        volumes:
            - ./vidjil-client/scripts:/entrypoints
            - ./vidjil-client/healthchecks:/healthchecks
            - $VOLUME_PATH2/log/nginx:/var/log/nginx
            - $VOLUME_PATH2/certs:/etc/letsencrypt/well-known
            - ./vidjil-client/ssl:/etc/nginx/ssl
            - ./vidjil-client/conf:/etc/vidjil
            - ./vidjil-client/conf/conf2.js:/etc/vidjil/conf.js
            - ../germline:/usr/share/vidjil/germline
        links:
            - uwsgi2:uwsgi
        depends_on:
            uwsgi2:
                condition: service_healthy
        networks:
            - vidjil2

    workers2:
        container_name: vidjil-workers2
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME WORKERS
        env_file:
            - '.env-default'
            - '.env'
        stdin_open: true
        tty: true
        command: bash /entrypoints/workers-entrypoint.sh
        volumes_from:
            - uwsgi2
        depends_on:
            uwsgi2:
                condition: service_healthy
            redis2:
                condition: service_started
            mysql2:
                condition: service_healthy
        links:
            - redis2:redis
            - mysql2:mysql
        networks:
            - vidjil2

    flower2:
        container_name: vidjil-flower2
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=$SERVICE_PREFIX_NAME FLOWER
        env_file:
            - '.env-default'
            - '.env'
        command: bash /entrypoints/flower-entrypoint.sh
        volumes_from:
            - uwsgi2
        depends_on:
            uwsgi2:
                condition: service_healthy
            workers2:
                condition: service_started
        ports:
            - "5556:5555"
        networks:
            - vidjil2

networks:
    vidjil2: # Use default driver  

