version: '2.1'
services:
   
    mysql2:
        image: mysql:8.0
        ports:
            - "4307:3306"
            - "43070:33060"
        volumes: []

    uwsgi2:
        image: vidjil/server:latest
        command: bash /entrypoints/uwsgi-entrypoint.sh
        # user: "www-data"
        volumes:
             # Local volume path
            - $VOLUME_PATH2/results:/mnt/result
            - $VOLUME_PATH2/results/results:/mnt/result/results
            - $VOLUME_PATH2/tmp:/mnt/result/tmp
            - $VOLUME_PATH2/uploads:/mnt/upload/uploads
            - $VOLUME_PATH2/databases:/usr/share/vidjil/server/py4web/apps/vidjil/databases
            # Use local vidjil repository
            - ../algo:/usr/share/vidjil/algo
            - ../browser:/usr/share/vidjil/browser
            - ../demo:/usr/share/vidjil/demo
            - ../demo:/mnt/data/src
            - ../doc:/usr/share/vidjil/doc
            - ./:/usr/share/vidjil/docker
            - ../server/py4web/apps/vidjil:/usr/share/vidjil/server/py4web/apps/vidjil
            - ../tools:/usr/share/vidjil/tools
            - $VOLUME_PATH2/binaries:/binaries
            # Tools and external scripts
            - ./vidjil-server/conf/defs-tools.py:/usr/share/vidjil/tools/defs.py
            - ./vidjil-server/conf/defs.py:/usr/share/vidjil/server/py4web/apps/vidjil/defs.py
            - ./scripts/:/usr/share/vidjil/tools/scripts
    nginx2:
        # user: "www-data"
        volumes:
            - ../browser:/usr/share/vidjil/browser
            - ./:/usr/share/vidjil/docker
            - ./vidjil-client/conf/conf2.js:/usr/share/vidjil/browser/js/conf.js

    fuse2:
        # user: "www-data"
        image: vidjil/server:latest
    workers2:
        # user: "www-data"
        image: vidjil/server:latest
    celery2:
        # user: "www-data"
        image: vidjil/server:latest
    flower2:
        # user: "www-data"
        image: vidjil/server:latest


