

dark.css : light.css style.less
	lessc style.less dark.css

light.css : style.less
	lessc --modify-var="default=#657b83" --modify-var="background=#eee8d5" --modify-var="highlight=#fdf6e3" --modify-var="select=#002b36" --modify-var="secondary=#93a1a1" --modify-var="border=#b3c1c1"  style.less light.css



