# See https://docs.docker.com/compose/compose-file/13-merge/ for more information
services:
    mysql:
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    uwsgi:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    fuse:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    nginx:
        image: vidjil/client:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'
        links:
            - uwsgi:uwsgi

    workers-all:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    workers-short:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    redis:
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'

    flower:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        env_file:
            - '.env.ci-review'
