version: "3"
services:

  mysql:
      image: mysql:5.7
      environment:
          - MYSQL_ROOT_PASSWORD=password
      volumes:
          - ./mysql/:/docker-entrypoint-initdb.d/
          - ./volumes/mysql:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  nginx:
      image: vidjil/client:latest
      links:
          - uwsgi:uwsgi
      environment:
          - DOMAIN_NAME=plop
      ports:
          - "80:80"
          - "443:443"
      command: bash /entrypoints/nginx-entrypoint.sh
      volumes:
          - /opt/vidjil/log/nginx:/var/log/nginx
          - /opt/vidjil/certs:/etc/letsencrypt/well-known
          - ./vidjil-client/ssl:/etc/nginx/ssl
          - ./vidjil-client/conf:/etc/vidjil
          - ../germline:/usr/share/vidjil/germline

  web:
    image: vidjil/server2:latest
    ports:
      - "8000:8000"
    #command: make -C /usr/share/vidjil/server/py4web start
    environment:
     - PYDAL_URI=mysql://vidjil:rootpass@mysql/vidjil
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - nginx


