version: "3"
services:

  mysql:
      image: mysql:5.7
      environment:
          - MYSQL_ROOT_PASSWORD=password
      volumes:
          - ./mysql/:/docker-entrypoint-initdb.d/
          - ./volumes/mysql:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  web:
    image: vidjil/server2:latest
    ports:
      - "8000:8000"
    command: bash /usr/share/vidjil/server/py4web make start
    environment:
     - PYDAL_URI=mysql://vidjil:rootpass@mysql/vidjil
    stdin_open: true
    tty: true
    depends_on:
      - mysql

  #postgres:
  #  restart: always
  #  image: postgres
  #  environment:
  #    - POSTGRES_USER=foo
  #    - POSTGRES_PASSWORD=bar
  #    - POSTGRES_DB=baz
  #    - POSTGRES_PORT=5432
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #     - ./data/postgres:/var/lib/postgresql/data