version: '2.1'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./mysql/:/docker-entrypoint-initdb.d/
            - ./volumes/mysql:/var/lib/mysql
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    uwsgi:
        image: vidjil/server:latest
        environment:
            - WEB2PY_ADMIN_PASSWORD=password
        command: bash /entrypoints/uwsgi-entrypoint.sh
        volumes_from:
            - fuse
        depends_on:
            mysql:
              condition: service_healthy
            fuse:
              condition: service_started
            postfix:
              condition: service_started
        links:
            - mysql:mysql
            - fuse:fuse
            - postfix:postfix
    fuse:
        image: vidjil/server:latest
        command: bash /entrypoints/fuse-entrypoint.sh
        volumes:
            - ../server/web2py/applications/vidjil/models:/usr/share/vidjil/server/web2py/applications/vidjil/models
            - ../server/web2py/applications/vidjil/scripts:/usr/share/vidjil/server/web2py/applications/vidjil/scripts
            - ../server/web2py/applications/vidjil/views:/usr/share/vidjil/server/web2py/applications/vidjil/views
            - ../server/web2py/applications/vidjil/controllers:/usr/share/vidjil/server/web2py/applications/vidjil/controllers

            - ./volumes/databases:/usr/share/vidjil/server/web2py/applications/vidjil/databases
            - ./volumes/results:/mnt/result/results
            - ./volumes/tmp:/mnt/result/tmp
            - ./volumes/uploads:/mnt/upload/uploads
            - ./volumes/log:/var/vidjil
            - ./volumes/log/uwsgi:/var/log/uwsgi
            - ./volumes/backup:/mnt/backup

            - ../demo:/mnt/data/src
            - ./vidjil-server/conf:/etc/vidjil
            - ./vidjil-server/scripts:/entrypoints
            - ../germline:/usr/share/vidjil/germline
    nginx:
        image: vidjil/client:latest
        depends_on:
            uwsgi:
              condition: service_started
        links:
            - uwsgi:uwsgi
        ports:
            - "80:80"
            - "443:443"
        command: bash /entrypoints/nginx-entrypoint.sh
        volumes:
            - ./volumes/log/nginx:/var/log/nginx
            - ./volumes/certs:/etc/letsencrypt/well-known
            - ./vidjil-client/conf:/etc/vidjil
            - ./vidjil-client/ssl:/etc/nginx/ssl
            - ../germline:/usr/share/vidjil/germline
            - ../browser:/usr/share/vidjil/browser
    workers:
        image: vidjil/server:latest
        command: bash /entrypoints/workers-entrypoint.sh
        volumes_from:
            - uwsgi
        depends_on:
            uwsgi:
              condition: service_started
            mysql:
              condition: service_healthy
        links:
            - mysql
            - postfix
    postfix:
        image: catatnight/postfix
        expose:
            - 587
        volumes:
            - ./postfix/ssl:/etc/postfix/certs
        environment:
            - maildomain=vidjil.org
            - smtp_user=vidjil:smtp_pass
