# ## Docker-compose
# You can set variables (as $MYSQL_ROOT_PASSWORD) values inside .env file
# Path variable and folders trees can be modified to your liking.

services:
    mysql:
        container_name: vidjil-mysql
        image: mysql:8.4
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} MYSQL
        env_file:
            - '.env.default'
        volumes:
            - ./mysql/:/docker-entrypoint-initdb.d/
            - ${VOLUME_PATH:-./volumes/vidjil/}/mysql:/var/lib/mysql
        healthcheck:
            test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
            timeout: 2s
            interval: 2s
            retries: 100
        networks:
            - vidjil

    redis:
        container_name: vidjil-redis
        image: redis
        networks:
            - vidjil

    uwsgi:
        container_name: vidjil-uwsgi
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} UWSGI
        env_file:
            - '.env.default'
        command: bash /entrypoints/uwsgi-entrypoint.sh
        stdin_open: true
        tty: true
        healthcheck:
            test: "bash /healthchecks/healthcheck_uwsgi.bash"
            timeout: 2s
            interval: 2s
            retries: 100
        depends_on:
            mysql:
                condition: service_healthy
        links:
            - mysql:mysql
            - redis:redis
        volumes:
            - ./vidjil-server/scripts:/entrypoints
            - ./vidjil-server/healthchecks:/healthchecks
            - ./vidjil-server/conf/defs-tools.py:/usr/share/vidjil/tools/defs.py
            - ./scripts/:/usr/share/vidjil/tools/scripts
            - ${VOLUME_PATH:-./volumes/vidjil/}/results:/mnt/result/results
            - ${VOLUME_PATH:-./volumes/vidjil/}/tmp:/mnt/result/tmp
            - ${VOLUME_PATH:-./volumes/vidjil/}/uploads:/mnt/upload/uploads
            - ${VOLUME_PATH:-./volumes/vidjil/}/tools:/usr/share/tools
            - ${VOLUME_PATH:-./volumes/vidjil/}/databases:/usr/share/vidjil/server/py4web/apps/vidjil/databases
            - ${VOLUME_PATH:-./volumes/vidjil/}/log:/var/vidjil
            - ${VOLUME_PATH:-./volumes/vidjil/}/log/uwsgi:/var/log/uwsgi
            - ${VOLUME_PATH:-./volumes/vidjil/}/backup:/mnt/backup
        networks:
            - vidjil

    fuse:
        container_name: vidjil-fuse
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} FUSE
        command: bash /entrypoints/fuse-entrypoint.sh
        env_file:
            - '.env.default'
        volumes_from:
            - uwsgi
        depends_on:
            mysql:
                condition: service_healthy
            uwsgi:
                condition: service_healthy
        links:
            - mysql:mysql
            - uwsgi:uwsgi
        networks:
            - vidjil

    nginx:
        container_name: vidjil-nginx
        image: vidjil/client:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} NGINX
        env_file:
            - '.env.default'
        ports:
            - "80:80"
            - "443:443"
        command: bash /entrypoints/nginx-entrypoint.sh
        volumes:
            - ./vidjil-client/scripts:/entrypoints
            - ./vidjil-client/healthchecks:/healthchecks
            - ${VOLUME_PATH:-./volumes/vidjil/}/log/nginx:/var/log/nginx
            - ${VOLUME_PATH:-./volumes/vidjil/}/certs:/etc/letsencrypt/well-known
            - ./vidjil-client/ssl:/etc/nginx/ssl
            - ./vidjil-client/conf:/etc/vidjil
        networks:
            - vidjil

    workers-all:
        container_name: vidjil-workers-all
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} WORKERS ALL
        env_file:
            - '.env.default'
        stdin_open: true
        tty: true
        command: bash /entrypoints/workers-entrypoint.sh all
        volumes_from:
            - uwsgi
        depends_on:
            mysql:
                condition: service_healthy
            uwsgi:
                condition: service_healthy # To prevent db creation racing issues
        links:
            - redis:redis
            - mysql:mysql
        networks:
            - vidjil

    workers-short:
        container_name: vidjil-workers-short
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} WORKERS SHORT
        env_file:
            - '.env.default'
        stdin_open: true
        tty: true
        command: bash /entrypoints/workers-entrypoint.sh short
        volumes_from:
            - uwsgi
        depends_on:
            mysql:
                condition: service_healthy
            uwsgi:
                condition: service_healthy # To prevent db creation racing issues
        links:
            - redis:redis
            - mysql:mysql
        networks:
            - vidjil

    flower:
        container_name: vidjil-flower
        image: vidjil/server:latest
        environment:
            - SERVICE_NAME=${SERVICE_PREFIX_NAME:-VIDJIL} FLOWER
        env_file:
            - '.env.default'
        command: bash /entrypoints/flower-entrypoint.sh
        volumes_from:
            - uwsgi
        depends_on:
            redis:
                condition: service_started
            uwsgi:
                condition: service_healthy # To prevent db creation racing issues
        links:
            - redis
        ports:
            - "5555:5555"
        networks:
            - vidjil

networks:
    vidjil: # Use default driver
