version: '2.1'


services:
    mysql:
        ports:
            - "5306:3306"
            - "53060:33060"
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
        container_name:
            "web2py_mysql"

    uwsgi:
        container_name:
            "web2py_uwsgi"

    fuse:
        volumes:
            # Data and opt
            # - /opt/vidjil/databases:/usr/share/vidjil/server/web2py/applications/vidjil/databases
            - ../germline:/usr/share/vidjil/germline
            - /home/florian/vidjil_toolkit:/mnt/data/src
            # # Browser & tools
            - ../code/tools:/usr/share/vidjil/tools:Z
            - ~/vidjil_scripts/pre:/usr/share/vidjil/tools/scripts
            # - ../code/vidjil-algo:/usr/share/vidjil/vidjil-algo:Z
            # Server local
            - ../code/server/web2py/applications/vidjil/controllers:/usr/share/vidjil/server/web2py/applications/vidjil/controllers
            - ../code/server/web2py/applications/vidjil/models:/usr/share/vidjil/server/web2py/applications/vidjil/models
            - ../code/server/web2py/applications/vidjil/modules:/usr/share/vidjil/server/web2py/applications/vidjil/modules
            - ../code/server/web2py/applications/vidjil/scripts:/usr/share/vidjil/server/web2py/applications/vidjil/scripts
            - ../code/server/web2py/applications/vidjil/static:/usr/share/vidjil/server/web2py/applications/vidjil/static
            - ../code/server/web2py/applications/vidjil/tests:/usr/share/vidjil/server/web2py/applications/vidjil/tests
            - ../code/server/web2py/applications/vidjil/views:/usr/share/vidjil/server/web2py/applications/vidjil/views
            - ../code/spike:/usr/share/vidjil/tools/source
            - ../code/bin:/binaries:Z
            # - ../opt/vidjil/tmp:/tmp:Z
        container_name:
            "web2py_fuse"

    nginx:
        volumes:
            # Browser & tools
            - ../code/browser:/usr/share/vidjil/browser:Z
            - ../code/spike:/source
        container_name:
            "web2py_nginx"

    workers:
        image: vidjil/server:latest
        container_name:
            "web2py_workers"
