version: "3"
services:

  mysql:
      image: mysql:5.7
      environment:
          - MYSQL_ROOT_PASSWORD=password
      volumes:
          - ./mysql/:/docker-entrypoint-initdb.d/
          - ./volumes/mysql2:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      ports:
          - "3307:3306"

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  uwsgi:
      image: vidjil/server2:latest
      command: bash /entrypoints/uwsgi-entrypoint.sh
      environment:
          - PYDAL_URI=mysql://vidjil:rootpass@mysql/vidjil
      volumes:
          - ../server/py4web/apps:/usr/share/vidjil/server/py4web/apps
      stdin_open: true
      tty: true
      depends_on:
          - mysql
      links:
          - mysql:mysql

  workers:
      image: vidjil/server2:latest
      command: bash /entrypoints/workers-entrypoint.sh
      depends_on:
          - uwsgi
          - redis
      links:
          - redis:redis

  celery:
      image: vidjil/server2:latest
      command: bash /entrypoints/celery-entrypoint.sh
      depends_on:
          - uwsgi
          - redis
      links:
          - redis:redis

  flower:
      image: vidjil/server2:latest
      command: bash /entrypoints/flower-entrypoint.sh
      depends_on:
          - workers
      ports:
          - "5555:5555"

  nginx:
      image: vidjil/client:latest
      links:
          - uwsgi:uwsgi
      environment:
          - DOMAIN_NAME=plop
      ports:
          - "80:80"
          - "443:443"
      command: 
            bash -c "make -C /usr/share/vidjil browser && bash /entrypoints/nginx-entrypoint.sh"
      volumes:
          - ./vidjil-client/scripts:/entrypoints
          - /opt/vidjil/log/nginx:/var/log/nginx
          - /opt/vidjil/certs:/etc/letsencrypt/well-known
          - ./vidjil-client/ssl:/etc/nginx/ssl
          - ./vidjil-client/conf:/etc/vidjil
          - ../germline:/usr/share/vidjil/germline



