# See https://docs.docker.com/compose/compose-file/13-merge/ for more information
services:
    mysql:
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        volumes:
            - ./ci/mysql:/var/lib/mysql

    uwsgi:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        command: bash /entrypoints/uwsgi-entrypoint.sh

    fuse:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        extra_hosts:
          - "fuse:127.0.0.1"

    nginx:
        image: vidjil/client:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
        links:
            - uwsgi:uwsgi
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST_NAME.server.ci.vidjil.org

    workers-all:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge

    workers-short:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge

    redis:
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge

    flower:
        image: vidjil/server:test
        container_name: !reset null
        ports: !reset []
        networks: !reset null
        network_mode: bridge
