#+TITLE: .analysis format
#+AUTHOR: The Vidjil team

The .analysis is a [[http://en.wikipedia.org/wiki/JSON][.json]] format describing customizations done by the user
(or by some automatic pre-processing) on the Vidjil browser. The browser
can load or save such files (and possibly from/to the server).

It is intended to be very small (a few kilobytes), compared to the
.data file that represents the actual data on clones (and that can
reach megabytes).

All settings in the .analysis file override the settings that could be
present in the .data file.


* Analysis file example

#+BEGIN_SRC js
    {
        "producer": "user Bob, via browser",
        "timestamp": "2014-09-01 12:00:11",
        "vidjil_json_version": "2014.XX",

        "samples": {
             "number": 2, 
             "names": ["diag", "fu1"],
             "order": [0, 1]
        },

        "clones": [
            {
                "id": "clone-845",
                "name": "Main LAL clone",
                "tag": "0",
            },
            {
                "id": "spikeE",
                "name": "spike",
                "sequence": "ATGACTCTGGAGTCTATTACTGTGCCACCTGGGATGTGAGTATTATAAGAAAC",
                "tag": "3",
                "expected": "0.1"
            }

        ],

        "clusters": [
            {
                [ "clone-845", "clone-821", "clone-147" ],
                [ "clone-5", "clone-10", "clone-179" ]
            }
        ],

        "data": {
             "qPCR": [0.83, 0.024],
        },

        "tags": {
            "0" : "main clone",
            "3" : "spike",
            "5" : "custom tag"
        }
    }
#+END_SRC


* Generic information for traceability

#+BEGIN_SRC js
   "producer": "",    // arbitrary string, user/software/options producing this file
   "timestamp": "",   // last modification date
   "vidjil_json_version": "2014.09", // version of the format
#+END_SRC


* 'Samples' element
#+BEGIN_SRC js
  {
    "number": 2,      // number of samples
    "names": [],      // custom sample names (with samples.number elements)
    "order": [],      // custom sample order (increasing order by default),
  }
#+END_SRC



* 'Clones' list

Each element in the 'clones' list describes properties of a clone.

#+BEGIN_SRC js
  {
    "id": "",        // clone identifier, must be unique [required]
                     //          Vidjil/algo output -> the 'window'  
                     //          Brno .clntab       -> clone sequence

    "name": "",      // clone custom name
                     // (the default name is computed from V/D/J information)

    "sequence": "",  // reference nt sequence (not really used now in the browser)
                     // (for special clones/sequences that are known,
                     //  such as standard/spikes or know patient clones)
 
    "tag": "",       // tag id from 0 to 7 (see below)
    "expected": ""   // expected abundance of this clone (between 0 and 1)
                     // this will create a normalization option in the 
                     // settings browser menu
 }
#+END_SRC


* 'Clusters' list

Each element in the 'clusters' list describe a list of clones that are 'merged'.
In the browser, it will be still possible to see them or to unmerge them.
The first clone of each line is used as a representative for the cluster.


* 'Data' list

Each element in the 'data' list is list of values (of size samples.number)
showing additional data, as for example qPCR levels or spike information.

In the browser, it will be possible to display these data and to normalize
against them (not implemented now).

* 'Tags' list

The 'tags' list describe the custom tag names.
The default tag names are defined in [[../browser/js/vidjil-style.js]].

#+BEGIN_SRC js
    "key" : "value"  // "key" is the tag id from 0 to 7 and "value" is the custom tag name attributed
#+END_SRC
