#+TITLE: .analysis format
#+AUTHOR: The Vidjil team

The .analysis is a [[http://en.wikipedia.org/wiki/JSON][.json]] format describing customizations done by the user
(or by some automatic pre-processing) on the Vidjil browser. The browser
can load or save such files (and possibly from/to the server).

It is intended to be very small (a few kilobytes), compared to the
.data file that represents the actual data on clones (and that can
reach megabytes).

All settings in the .analysis file override the settings that could be
present in the .data file.


* Analysis file example

#+BEGIN_SRC js
    {
        "producer": "user Bob, via browser",
        "timestamp": "2014-09-01 12:00:11",
        "vidjil_json_version": "2014.XX",

        "samples": {
             "number": 2, 
             "names": ["diag", "fu1"],
             "order": [0, 1]
        },

        "clones": [
            {
                "window": "ATGTGAGTAT",
                "sequence": "ATGACTCTGGAGTCTATTACTGTGCCACCTGGGATGTGAGTATTATAAGAAAC",
                "tag": "0"
                "name": "plop",
                "expected": "0.1"
            }
          // TODO: mettre une deuxième window, et des noms plus réalistes
        ],

        "clusters": [
            {
                [ "clone-845", "clone-821", "clone-147" ],
                [ "clone-5", "clone-10", "clone-179" ]
            }
        ],

        "tags": {
            "0" : "main clone",
            "3" : "spike",
            "5" : "custom tag"
        }
    }
#+END_SRC


* Generic information for traceability

#+BEGIN_SRC js
   "producer": "",    // arbitrary string, user/software/options producing this file
   "timestamp": "",   // last modification date
   "vidjil_json_version": "2014.09", // version of the format
#+END_SRC


* 'Samples' element
#+BEGIN_SRC js
  {
    "number": 2,      // number of samples
    "names": [],      // custom sample names (with samples.number elements)
    "order": [],      // custom sample order (increasing order by default),
  }
#+END_SRC



* 'Clones' list

Each element in the 'clones' list describes properties of a clone.
The minimum required fields are "window" and/or "sequence".

#+BEGIN_SRC js
  {
    "window": "",    // clone identifier
                     //          Vidjil/algo output -> the 'window'  
                     //          Brno .clntab       -> clone sequence
    "sequence": "",  // clone nt sequence
    "tag": "",       // tag id from 0 to 7 (see below)
    "name": "",      // custom name, will replace the clone default name
    "expected": ""   // expected abundance of this clone (between 0 and 1)
                     // this will create a normalization option in the 
                     // settings browser menu
 }
#+END_SRC


* 'Clusters' list

Each element in the 'clusters' list describe a list of clones that are 'merged'.
In the browser, it will be still possible to see them or to unmerge them.
The first clone of each line is used as a representative for the cluster.


* 'Tags' list

The 'tags' list describe the custom tag names.
The default tag names are defined in [[../browser/js/vidjil-style.js]].

#+BEGIN_SRC js
    "key" : "value"  // "key" is the tag id from 0 to 7 and "value" is the custom tag name attributed
#+END_SRC
