#+TITLE: .analysis format

The .analysis is a [[http://en.wikipedia.org/wiki/JSON.json][.json]] format describing customizations done by the user
(or by some automatic pre-processing) on the Vidjil browser. The browser
can load or save such files (and possibly from/to the server).

It is intended to be very small (some kilobytes), compared to the
.data file that represent the actual data on clones (and that can
reach megabytes).

All settings in the .analysis file override the settings that could be
present in the .data file.


* Analysis file example

#+BEGIN_SRC js
    {
        "custom": [
            {
                "window": "ATGTGAGTAT",
                "sequence": "ATGACTCTGGAGTCTATTACTGTGCCACCTGGGATGTGAGTATTATAAGAAAC",
                "tag": "0"
                "name": "plop",
                "expected": "0.1"
            }
          // TODO: mettre une deuxième window, et des noms plus réalistes
        ],


        "cluster": [
            {
                "l": "ACTGTGCCACCTGGGATGTGAGTATTATAAGAAACTCTTT",
                "f": "TGCCACCTGGGATGTGAGTATTATAAAGAAACTCTTTGGC"
            }
        ],


        "time": [
            "diag",
            "follow up 1"
        ],

        "time_order": [
            0,
            1
        ],

        "tag": {
            "0" : "main clone",
            "3" : "spike",
            "5" : "custom tag"
        }
    }
#+END_SRC


* General layout

#+BEGIN_SRC js
    "custom" : [] ,   // customized properties of clone (see below, custom field)
    "cluster": [],    // manual clustering  (see cluster field)
    "tag": []         // custom tag name (see tag field)

    "time" : [],      // custom sample names (list length must match the number of samples)
    "time_order": [], // custom sample order (increasing order by default),
#+END_SRC


* Custom list: Describing clone properties

Each element in the 'custom' list describe properties of a clone.
The minimum requiered fields are "window" and/or "sequence".

#+BEGIN_SRC js
  {
    "window": "",    // clone identifier
                     //          Vidjil/algo output -> the 'window'  
                     //          Brno .clntab       -> clone sequence
    "sequence": "",  // clone nt sequence
    "tag": "",       // tag id from 0 to 7 (see below)
    "name": "",      // custom name, will replace the clone default name
    "expected": ""   // expected abundance of this clone (between 0 and 1), this will create a normalization option in the settings browser menu
 }
#+END_SRC


* Cluster list: merging clones

Each element in the 'cluster' list says that two clones should be merged.
In the browser, they will be 'merged'. It will be still possible to see them or to unmerge them.

#+BEGIN_SRC js
  {
    "l": "",         // identifier of the first clone (will be used as a representative for the cluster)
    "f": ""          // identifier of the second clone
  }
#+END_SRC

Merging more than two clones has to be done in several 'cluster' elements.
In a near future, it will be possible to put a list of windows instead of pair of windows.


* Tag list

The 'tag' list describe the tag names.
The default tag names are defined in [[../browser/js/vidjil-style.js]].

#+BEGIN_SRC js
    "key" : "value"  // "key" is the tag id from 0 to 7 and "value" is the custom tag name attributed
#+END_SRC
