#+TITLE: Vidjil -- Documentation
#+AUTHOR: The Vidjil team (Mathieu, Mikaël, Aurélien, Florian, Marc, Ryan and Tatiana)
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org-mode.css" />

[[http://www.vidjil.org][Vidjil]] is an open-source platform for the analysis of high-throughput
sequencing data from lymphocytes.  [[http://en.wikipedia.org/wiki/V(D)J_recombination][V(D)J recombinations]] in lymphocytes are
essential for immunological diversity. They are also useful markers of
pathologies, and in leukemia, are used to quantify the minimal residual
disease during patient follow-up. High-throughput sequencing (NGS/HTS) now
enables the deep sequencing of a lymphoid population with dedicated [[http://omictools.com/rep-seq-c424-p1.html][Rep-Seq]]
methods and software.

** Web application, user documentation
   :PROPERTIES:
   :CUSTOM_ID: web-application-user-documentation
   :END:

-  Tutorial "Mastering the Vidjil web application": [[./tutorial/mastering-vidjil.html][english]] ([[./tutorial/mastering-vidjil.pdf][pdf]]), [[./tutorial/mastering-vidjil-fr.html][français]]
  ([[./tutorial/mastering-vidjil-fr.pdf][pdf]]). Start by this tutorial to have an overview of Vidjil.
-  Web application [[./user.html][user manual]]
-  [[http://app.vidjil.org/][Demo access]] to the patient, experiment and sample server
-  [[http://www.vidjil.org/data/][Public datasets]] supporting Vidjil publications

** Algorithm, web application, server, developper documentation
   :PROPERTIES:
   :CUSTOM_ID: algorithm-web-application-server-developper-documentation
   :END:

-  [[./algo.html][Algorithm documentation]]
-  [[./format-analysis.html][Encoding clones with V(D)J recombinations]], specification of the .json file format
-  [[./server.html][Server documentation]]

These documentations and additional developer and maintainer documentation
are availaible from the [[https://git.vidjil.org/tree/master/doc][doc/]] directory in the source files.
** Further help
   :PROPERTIES:
   :CUSTOM_ID: further-help
   :END:

Further help can always be asked to [[mailto:contact@vidjil.org][contact@vidjil.org]]. We can also arrange
phone or Skype meeting.
