#+TITLE: Vidjil -- Server Manual

This is the preliminary help of the upcomping Vidjil server.
This help is intended for server administrators. 
Users of the should consult the browser help.

* Installing and running the vidjil server

These installation instruction are for Ubuntu server 14.04

** Requirements
    apt-get install git
    apt-get install g++
    apt-get install make
    apt-get install unzip

** Vidjil server installation and initialization
   Enter in the =server/= directory.

   If you just want to do some tests without installing a real web server,
   then launch =make install_web2py_standalone=. In the other case, launch
   =make install_web2py=.

   The process for installing Vidjil server together with a real web server
   will be detailed in the future.

* Testing the server
  If you develop on the server, or just want to check if everything is ok, you
  should launch the server tests.

  First, you should have a working fuse server by launching =make
  launch_fuse_server= (just launch it once, then it is running in the
  background and can be killed with =make kill_fuse_server=).

  Then you can launch the tests with =make unit=.
