#!/bin/sh

echo <<EOF
Please pay attention that the Stanford_S22 dataset comes from Boyd,
S. D., et al. Individual variation in the germline Ig gene repertoire inferred
from variable region gene rearrangements. J Immunol, 184(12), 6986–92.
EOF

wget -q -O- http://www.vidjil.org/seqs/Stanford_S22.tar.gz | tar xvzf -
