
test_server_api:
  stage: test_server_api
  extends:
    - .test_server_base_dind
  script: &test_cypress_server_script
    - mkdir -p logs/before; cd docker; for service in `docker compose config | yq '.services[]|key'`; do docker logs vidjil-${service} > ../logs/before/${service}.log 2>&1; done; cd ..
    - docker pull "registry.gitlab.inria.fr/vidjil/vidjil/cypress_with_browsers:$CYPRESS_DOCKER_VERSION"
    - >
      docker run --rm
      -v $PWD/$CYPRESS_PATH:/app/cypress
      -v $PWD:/app/vidjil
      -v "$PWD/docker/ci/cypress.config.js":"/app/cypress.config.js"
      -v "$PWD/docker/ci/script_api.bash":"/app/script.bash"
      -v "$PWD/docker/ci/.coveragerc":"/app/.coveragerc"
      --env HOST=$HOST
      --env PROJECT=$PROJECT
      --env URL=$URL
      --env CI_PASSWORD_TEST=$CI_PASSWORD_TEST
      --shm-size=1GB
      --network="host"
      "registry.gitlab.inria.fr/vidjil/vidjil/cypress_with_browsers:$CYPRESS_DOCKER_VERSION" bash script.bash $TEST_FILES
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: tools/tests/test_api_report.xml
      coverage_report:
        coverage_format: cobertura
        path: tools/tests/api_coverage.xml
    paths:
      - docker/.env*
      - docker/*.yml
      - docker/vidjil-*
      - browser/js/conf.js
      - tools/tests/test_api_report.xml
      - logs
      - coverage.xml
    expire_in: 7 day
    when: always
  variables:
    HOST: local
  rules:
    - if: '$CI_COMMIT_BRANCH !~ /dev/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH !~ /release-web-.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*s.*\/.*$/'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*t.*\/.*$/'
      when: on_success
  needs:
    - [build_test_server_docker]

