
.vidjil-algo_template: &vidjil-algo
  image: gcc:8
  before_script:
    - apt-get update
    - apt-get install -y lcov time
    - !reference [.before_script_global]
  only:
    - /^feature-.*a.*\/.*$/
    - schedules
  needs: []
  tags:
    - cidocker

.coverage_dependency:
  artifacts: &lcov_artifact
    paths:
      - algo/lcov_test_*.filtered
    expire_in: 1 week

## vidjil-algo, regular tests

algo_unit:
  <<: *vidjil-algo
  stage: test_unit
  script: make -C algo unit_coverage
  artifacts:
    <<: *lcov_artifact

algo_should:
  <<: *vidjil-algo
  stage: test_functional
  script: make -C algo should_coverage
  artifacts:
    <<: *lcov_artifact
    reports:
      junit: algo/tests/should.xml

algo_shouldvdj:
  <<: *vidjil-algo
  stage: test_shouldvdj
  script: make -C algo shouldvdj_coverage
  artifacts:
    <<: *lcov_artifact

algo_coverage:
  <<: *vidjil-algo
  stage: coverage
  coverage: /^\s*lines\.*:\s+([0-9.]+\%)/
  script:
    - make -C algo lcov_reports
    - mv algo/reports/ coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week


## vidjil-algo, other tests

profiling_algo:
  stage: benchmark
  image: gcc:9
  before_script:
    - apt-get update
    - apt-get install -y wget python3 tar libgoogle-perftools4 libgoogle-perftools-dev google-perftools graphviz
  script:
    - make demo data germline
    - make DEBUG="-g"
    - LIB_PROFILE=$(find /usr/lib -name libprofiler.so)
    - CPUPROFILE=vidjil.cpu LD_PRELOAD="$LIB_PROFILE" ./vidjil-algo -g germline -r 1 demo/LIL-L4.fastq.gz
    - LIB_MALLOC=$(find /usr/lib -name libtcmalloc.so)
    - HEAPPROFILE=vidjil.mem LD_PRELOAD="$LIB_MALLOC" ./vidjil-algo -g germline -r 1 demo/LIL-L4.fastq.gz

    - google-pprof --lines --text vidjil-algo vidjil.cpu
    - echo "###########################################"
    - google-pprof --lines --text vidjil-algo vidjil.mem.*
    - google-pprof --lines --pdf vidjil-algo vidjil.cpu > vidjil-cpu.pdf
    - google-pprof --lines --pdf vidjil-algo vidjil.mem.* > vidjil-mem.pdf
  artifacts:
    paths:
      - vidjil-*.pdf
      - vidjil.cpu
      - vidjil.mem.*
  when: manual
  only:
    - /^feature-.*a.*\/.*$/
  tags:
    - cidocker
    
